export {
  GUEST_INVITE_ERROR_PARAM,
  GUEST_INVITE_EXPIRED_VALUE,
  guestInviteErrorFromSearch,
  guestInviteExpiredLocation,
  guestInviteSuccessLocation,
  guestInviteToken,
  isGuestInvitePath,
  isLegalDocumentPath,
  isLoginPath,
  isPublicHomePath,
  looksLikeStaticAsset,
  navigationDecision,
  normalizePathname,
  type NavigationDecision,
} from '../api/_lib/app-routes'
